### ISSUE TITLE
Strange F821 false positive on flake8 git main

### ISSUE THREAD

**Issue by nyuszika7h** [snok/flake8-type-checking#71]
When using this extension with PyCQA/flake8@8c1ed24, it triggers false F821 errors from pyflakes. The error does not happen with flake8 4.0.1 from PyPI. It only seems to happen on top-level code, ~~and goes away if a non-empty `TYPE_CHECKING` block with any import (even an unused one) is present~~.

# Minimal working example

```py
import os

os.urandom(8)
```

pyproject.toml:
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["nyuszika7h <nyuszika7h@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
flake8 = {git = "https://github.com/PyCQA/flake8.git", rev = "main"}
flake8-type-checking = "^1.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

flake8 output:
```
❯ flake8 test.py
test.py:3:1: F821 undefined name 'os'
```

---

~~The following does not trigger the error:~~
```py
import os                                               
from typing import TYPE_CHECKING                        
                                                        
if TYPE_CHECKING:                                       
    import sys  # random import to demonstrate, not used
                                                        
os.urandom(8)                                           
```
