### ISSUE TITLE
Errors TC1 aren't raised with flakeheaven

### ISSUE THREAD

**Issue by ShaiAvr** [snok/flake8-type-checking#75]
I am using [flakeheaven](https://flakeheaven.readthedocs.io/en/latest/) (a maintained fork of the more known [flakehell](https://github.com/life4/flakehell) framework). I also use TC1 error ranges because I prefer postponed evaluation of annotations rather than string literals. However, I can't seem to generate any TC1 error. Take this code for example:
```python
from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np


if TYPE_CHECKING:
    from collections.abc import Iterable
    from typing import SupportsFloat
    import numpy.typing as npt


class Vector:
    _data: npt.NDArray[np.float64]

    def __init__(self, coordinates: Iterable[SupportsFloat | str]) -> None:
        ...

    @classmethod
    def of(cls) -> "Vector":
        pass
```
I would expect to get a `TC101` error telling me that I don't need a string literal for `Vector.of` return type. However, this code passes with no linter errors. On the other hand, this similar, but still wrong code:
```python
from typing import TYPE_CHECKING

import numpy as np


if TYPE_CHECKING:
    from collections.abc import Iterable
    from typing import SupportsFloat
    import numpy.typing as npt


class Vector:
    _data: npt.NDArray[np.float64]

    def __init__(self, coordinates: Iterable[SupportsFloat | str]) -> None:
        ...

    @classmethod
    def of(cls) -> Vector:
        pass
```
doesn't generate a `TC100` error telling me I am missing a `from __future__ import annotations` import. All I get is a regular flake8 `F821` error because of the "undefined" name `Vector`.

I tried enabling `TC1` range in the `pyproject.toml` file as described in the [documentation](https://flakeheaven.readthedocs.io/en/latest/config.html#plugins) (`select` and `enable-extensions` are [ignored](https://flakeheaven.readthedocs.io/en/latest/config.html#ignored-options) in flakeheaven), but nothing works.

Here are the relevant parts of the `pyproject.toml` file:
```toml
[tool.poetry]
version = "0.1.0"
description = ""
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.22.2"

[tool.poetry.dev-dependencies]
ipython = "^8.1.1"
black = "^22.1.0"
mypy = "^0.931"
pre-commit = "^2.17.0"
isort = "^5.10.1"
flakeheaven = "^0.11.1"

# Flake8 plugins
flake8-type-checking = "^1.3.2"
flake8-bugbear = "^22.1.11"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.8.0"
flake8-simplify = "^0.18.1"

[tool.flakeheaven]
format = "grouped"
show_source = true
max_line_length = 88
max_complexity = 18
exclude = [".git", ".venv", "__pycache__", "docs/source/conf.py", "old", "build", "dist"]

[tool.flakeheaven.plugins]
"flake8-*" = ["+*"]  # Should be enough to work
# flake8-type-checking = ["+TC0*", "+TC1*"]  # Doesn't generate TC1 errors
flake8-type-checking = ["+*"]  # Doesn't generate TC1 errors
```
